name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout el código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar las credenciales de AWS
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Paso 3: Crear la instancia EC2
      - name: Create EC2 Instance
        id: create_ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0453ec754f44f9a4a \
            --instance-type t2.micro \
            --key-name github-actions \
            --security-group-ids sg-069bcf83cf20c922d \
            --subnet-id subnet-0771bfc4dab8295c7 \
            --associate-public-ip-address \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "Created EC2 instance with ID: $INSTANCE_ID"

          # Guardamos el ID de la instancia como salida
          echo "::set-output name=instance_id::$INSTANCE_ID"
          
          # Obtener la IP pública de la instancia
          EC2_PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)

          echo "EC2 public IP: $EC2_PUBLIC_IP"
          echo "::set-output name=ec2_public_ip::$EC2_PUBLIC_IP"

      # Paso 4: Esperar a que la instancia esté en estado 'running'
      - name: Wait for EC2 instance to be running
        run: |
          echo "Waiting for EC2 instance to be in 'running' state..."
          aws ec2 wait instance-running --instance-ids ${{ steps.create_ec2.outputs.instance_id }}
          echo "EC2 instance is now in 'running' state."

      # Paso 5: Crear la AMI desde la instancia EC2
      - name: Create AMI from EC2 instance
        id: create_ami
        run: |
          # Crear la imagen (AMI) desde la instancia EC2 utilizando el ID de la instancia
          AMI_ID=$(aws ec2 create-image \
            --instance-id ${{ steps.create_ec2.outputs.instance_id }} \
            --name "mi-ami-personalizada" \
            --no-reboot \
            --query 'ImageId' \
            --output text)

          echo "Created AMI with ID: $AMI_ID"
          echo "::set-output name=ami_id::$AMI_ID"

      # Paso 6: Descargar y configurar la clave SSH
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions.pem
          chmod 600 ~/.ssh/github-actions.pem

      # Paso 7: Copiar los archivos a la instancia EC2
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/github-actions.pem -r ./ ec2-user@${{ steps.create_ec2.outputs.ec2_public_ip }}:/home/ec2-user/app
